import { Inter } from 'next/font/google';
import MasterProvider from './MasterProvider';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<head />
			<body className="bg-slate-900 text-slate-400">
				<MasterProvider>{children}</MasterProvider>
			</body>
		</html>
	);
}
